// Even if the condition written is wrong the loop has to be executed atlest 1 time in Do-While loop...
// major diff : while-loop : check first and then execute it ; Do-While-loop : Execute it first and then check if the condition is corre t or not.
